### ISSUE TITLE
Support for optimize

### ISSUE THREAD

**Issue by domoritz** [Aluriak/clyngor#1]
If I have soft constraints, this library gives me multiple results and also does not return the penalty for the different optimizations. 

I saw `yield_stats` but it's not passed through from `clyngor.solve`.

**Comment by Aluriak** [comment]
I just updated clyngor 0.1.0, that now handle access to stats and optimizations.

    solver = clyngor.solve(...)
    solver.stats  # it's a dict

    for answer, opt in solver.with_optimization:
        # opt is the optimization score

Note that the stats are copy pasted raw into a dict, without any consideration for the eventual doublons or hierarchy.
