### ISSUE TITLE
Add conda package

### ISSUE THREAD

**Issue by domoritz** [Aluriak/clyngor#10]
It would be nice if clyngor was available as a conda package through https://conda-forge.org/. Clingo has a conda package.

**Comment by Aluriak** [comment]
Packaging of clyngor is standard. I do not know conda, but i would be surprised they do not provide an automated way to directly transfert pypi package to their package manager.

**Comment by Aluriak** [comment]
[Some sources](https://stackoverflow.com/a/45361152/3077939) show how to do this, and also mitigates the interests of making a conda package.

**Comment by ArnaudBelcour** [comment]
Also, if you use clyngor with clingo installed by conda, there is some issues with the parsing (issue #7 ).

**Comment by Aluriak** [comment]
fixed since 261fabafc1c
