### ISSUE TITLE
Use JSON output

### ISSUE THREAD

**Issue by domoritz** [Aluriak/clyngor#2]
Why doesn't this library parse the JSON output rather than the raw string output from clingo?

**Comment by Aluriak** [comment]
I want to access models as they are yielded by clingo, not to wait for the solving to end.

This is quite simple using the default output, but managing that in json is not easy with the default stdlib module AFAIK.

However, it should be possible to use the JSON output anyway (without the JSON parser). Would be handy to get the final stats (as requested in #1 )

**Comment by domoritz** [comment]
That's a good reason that I did not consider. Thanks for the explanation and the great library.
