### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by synapticarbors** [Aluriak/clyngor#26]
The `MANIFEST.in` makes reference to a license file, but that file is not in the repository. There is currently an effort underway to package `clyngor` on conda-forge (https://github.com/conda-forge/staged-recipes/pull/11306), and it would be helpful, if possible to:

1. Clarify which version of GPL licenses this package
2. Add a license file so that it's included in the source distribution.

**Comment by Aluriak** [comment]
Cool. Let it be GPLv3. What do you need for (1), apart from (2) being fixed and `setup.cfg` being updated ?

**Comment by raivivek** [comment]
@Aluriak I think just adding the GPL3 license file `LICENSE` and updating the `setup.cfg` should then resolve all the issues for the PR.

**Comment by raivivek** [comment]
@Aluriak I spoke too soon. Could you also create a new tagged released with the new changes?

**Comment by Aluriak** [comment]
Done !

**Comment by raivivek** [comment]
Thanks! The recipe is now merged.
