### ISSUE TITLE
Support running clingo without creating temporary files

### ISSUE THREAD

**Issue by domoritz** [Aluriak/clyngor#3]
The program can be passed via stdin if there are no other files needed. It would be nice to support this to speed up solving.

**Comment by Aluriak** [comment]
Yes, could be cool. I will however not be able to patch that before the next week.

**Comment by domoritz** [comment]
Thank you! There is not rush for me as I have some special requirements and went on to write my own logic for this. here is how I call clingo to pass data via stdin: https://github.com/domoritz/draco/blob/655c8f59ea7b02a3076444b01ee621f7d993157a/draco/run.py#L52.

**Comment by Aluriak** [comment]
Hi ! Finally i took the time to do this with 643be541 (can't push to github now for some reason). Its available on pypi (0.3.2). The new behavior is too pass data via stdin when only inline data is provided.

Thanks for your contribution !

**Comment by domoritz** [comment]
Thank you!

**Comment by domoritz** [comment]
Is the code for this change on Github? The latest release here is 0.3.

**Comment by Aluriak** [comment]
Sorry, i didn't push it. Its done now.

**Comment by domoritz** [comment]
Can you push your tags as well? I see only the 0.3 release at https://github.com/Aluriak/clyngor/releases

**Comment by Aluriak** [comment]
Done !

**Comment by Aluriak** [comment]
you are welcome !
